### ISSUE TITLE
Could you please offer some instructions of CMake?

### ISSUE THREAD

**Issue by cider-apple** [cclvi256/DSA-Labs#1]
As you've said, you have written these code in C++, and CMake is utilised to build them. So could you add some instructions for CMake usage?

**Comment by cclvi256** [comment]
If you use the g++ command, in fact, you can change the `#include` commands to adapt to the path of the headers and compile the source files all in a g++ command. This will be more easier, especially for Windows. But if you're using Visual Studio Code, maybe CMake is better.

Or you can use `cmake ..` in the direcroty ./build, and then use `make` in the same directory to generate the executable files.
